# Generated by Django 5.2.2 on 2025-06-07 17:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredient_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='Is this item available for purchase or as an option?'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_standalone_item',
            field=models.BooleanField(default=True, help_text='Can this item be purchased on its own from the menu?'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='nutritional_info',
            field=models.JSONField(blank=True, help_text="e.g., {'calories': 500, 'protein_g': 25}", null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='Enter phone number in international format', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0.0, help_text='Price difference. Can be positive (upcharge) or negative (discount).', max_digits=6)),
                ('is_default', models.BooleanField(default=False, help_text='Is this option selected by default?')),
                ('item', models.ForeignKey(help_text='The MenuItem being offered as a choice.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='restaurant.optionchoice'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='restaurant.optionchoice'),
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Sides', 'Choose your sauces'", max_length=100)),
                ('min_selection', models.PositiveIntegerField(default=1)),
                ('max_selection', models.PositiveIntegerField(default=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='restaurant.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='optionchoice',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='restaurant.optiongroup'),
        ),
    ]
